//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Recruiment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhanvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nhanvien()
        {
            this.hopdonglaodongs = new HashSet<hopdonglaodong>();
        }
    
        public int nv_id { get; set; }
        public string nv_ten { get; set; }
        public Nullable<System.DateTime> nv_ngaysinh { get; set; }
        public string nv_diachi { get; set; }
        public string nv_sdt { get; set; }
        public Nullable<bool> nv_gioitinh { get; set; }
        public Nullable<int> pb_id { get; set; }
        public Nullable<int> cvu_id { get; set; }
        public Nullable<int> tdhv_id { get; set; }
        public Nullable<int> lg_bacluong { get; set; }
        public string nv_tinhtrang { get; set; }
        public Nullable<int> tt_id { get; set; }
        public Nullable<bool> loai { get; set; }
        public string nv_email { get; set; }
    
        public virtual chucvu chucvu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hopdonglaodong> hopdonglaodongs { get; set; }
        public virtual loai loai1 { get; set; }
        public virtual luong luong { get; set; }
        public virtual phongban phongban { get; set; }
        public virtual tinhtrang tinhtrang { get; set; }
        public virtual trinhdohocvan trinhdohocvan { get; set; }
    }
}
