//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Recruiment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieutuyendung
    {
        public int ptd_id { get; set; }
        public string ptd_ten { get; set; }
        public System.DateTime ptd_ngaysinh { get; set; }
        public string ptd_sdt { get; set; }
        public bool ptd_gioitinh { get; set; }
        public string ptd_chucvu { get; set; }
        public string ptd_email { get; set; }
        public int ttptd_id { get; set; }
        public System.DateTime ptd_ngaydangphieu { get; set; }
    
        public virtual tinhtrangphieutuyendung tinhtrangphieutuyendung { get; set; }
    }
}
