//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Recruiment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tinhtrangdottuyendung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tinhtrangdottuyendung()
        {
            this.tuyendungs = new HashSet<tuyendung>();
        }
    
        public int tttd_id { get; set; }
        public string tttd_ten { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tuyendung> tuyendungs { get; set; }
    }
}
