//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Candidate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hopdonglaodong
    {
        public int hdld_id { get; set; }
        public int nv_id { get; set; }
        public string hdld_loai { get; set; }
        public System.DateTime hdld_ngaybatdau { get; set; }
        public System.DateTime hdld_ngayketthuc { get; set; }
    
        public virtual nhanvien nhanvien { get; set; }
    }
}
