//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Candidate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class luong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public luong()
        {
            this.nhanviens = new HashSet<nhanvien>();
        }
    
        public int lg_bacluong { get; set; }
        public int lg_luongcoban { get; set; }
        public int lg_hesoluong { get; set; }
        public int lg_hesophucap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nhanvien> nhanviens { get; set; }
    }
}
